# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(781, 568)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_vergleicher = QtWidgets.QWidget()
        self.tab_vergleicher.setObjectName("tab_vergleicher")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_vergleicher)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_input = QtWidgets.QLabel(self.tab_vergleicher)
        self.lbl_input.setObjectName("lbl_input")
        self.gridLayout.addWidget(self.lbl_input, 0, 0, 1, 1)
        self.le_input1 = QtWidgets.QLineEdit(self.tab_vergleicher)
        self.le_input1.setObjectName("le_input1")
        self.gridLayout.addWidget(self.le_input1, 1, 0, 1, 1)
        self.pb_vergleiche = QtWidgets.QPushButton(self.tab_vergleicher)
        self.pb_vergleiche.setAutoDefault(False)
        self.pb_vergleiche.setDefault(True)
        self.pb_vergleiche.setFlat(False)
        self.pb_vergleiche.setObjectName("pb_vergleiche")
        self.gridLayout.addWidget(self.pb_vergleiche, 1, 1, 1, 1)
        self.le_input2 = QtWidgets.QLineEdit(self.tab_vergleicher)
        self.le_input2.setObjectName("le_input2")
        self.gridLayout.addWidget(self.le_input2, 2, 0, 1, 1)
        self.lbl_ergebnis = QtWidgets.QLabel(self.tab_vergleicher)
        self.lbl_ergebnis.setObjectName("lbl_ergebnis")
        self.gridLayout.addWidget(self.lbl_ergebnis, 3, 0, 1, 2)
        self.tb_result = QtWidgets.QTextBrowser(self.tab_vergleicher)
        self.tb_result.setEnabled(True)
        self.tb_result.setObjectName("tb_result")
        self.gridLayout.addWidget(self.tb_result, 4, 0, 1, 2)
        self.tabWidget.addTab(self.tab_vergleicher, "")
        self.tab_bmi = QtWidgets.QWidget()
        self.tab_bmi.setObjectName("tab_bmi")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_bmi)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pb_berechne_bmi = QtWidgets.QPushButton(self.tab_bmi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_berechne_bmi.sizePolicy().hasHeightForWidth())
        self.pb_berechne_bmi.setSizePolicy(sizePolicy)
        self.pb_berechne_bmi.setObjectName("pb_berechne_bmi")
        self.gridLayout_3.addWidget(self.pb_berechne_bmi, 2, 1, 1, 1)
        self.lbl_bmi = QtWidgets.QLabel(self.tab_bmi)
        self.lbl_bmi.setObjectName("lbl_bmi")
        self.gridLayout_3.addWidget(self.lbl_bmi, 5, 0, 1, 1)
        self.le_height_m = QtWidgets.QLineEdit(self.tab_bmi)
        self.le_height_m.setObjectName("le_height_m")
        self.gridLayout_3.addWidget(self.le_height_m, 3, 0, 1, 1)
        self.lbl_height_m = QtWidgets.QLabel(self.tab_bmi)
        self.lbl_height_m.setToolTipDuration(-1)
        self.lbl_height_m.setObjectName("lbl_height_m")
        self.gridLayout_3.addWidget(self.lbl_height_m, 2, 0, 1, 1)
        self.le_weight_kg = QtWidgets.QLineEdit(self.tab_bmi)
        self.le_weight_kg.setObjectName("le_weight_kg")
        self.gridLayout_3.addWidget(self.le_weight_kg, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 4, 0, 1, 1)
        self.lbl_weight_kg = QtWidgets.QLabel(self.tab_bmi)
        self.lbl_weight_kg.setObjectName("lbl_weight_kg")
        self.gridLayout_3.addWidget(self.lbl_weight_kg, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 2, 2, 1, 1)
        self.tabWidget.addTab(self.tab_bmi, "")
        self.gridLayout_2.addWidget(self.tabWidget, 4, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_input.setText(_translate("MainWindow", "Daten"))
        self.le_input1.setPlaceholderText(_translate("MainWindow", "String 1"))
        self.pb_vergleiche.setText(_translate("MainWindow", "vergleiche Strings"))
        self.le_input2.setPlaceholderText(_translate("MainWindow", "String 2"))
        self.lbl_ergebnis.setText(_translate("MainWindow", "Ergebnis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_vergleicher), _translate("MainWindow", "Vergleicher"))
        self.pb_berechne_bmi.setText(_translate("MainWindow", "Berechne BMI"))
        self.lbl_bmi.setText(_translate("MainWindow", "BMI:"))
        self.lbl_height_m.setText(_translate("MainWindow", "Größe in m"))
        self.lbl_weight_kg.setText(_translate("MainWindow", "Körpergewicht in Kg"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_bmi), _translate("MainWindow", "BMI"))
